### ISSUE TITLE
ModuleNotFoundError: No module named 'google.protobuf'

### ISSUE THREAD

**Issue by DavidDreven** [jkjung-avt/tensorrt_demos#270]
I have some problems in Demo #5: YOLOv4
I'm trying to convert the pre-trained yolov3/yolov4 COCO  to ONNX.

When I run:
$ python3 yolo_to_onnx.py -m yolov4-608

I get the following error:

Traceback (most recent call last):
  File "yolo_to_onnx.py", line 61, in <module>
    import onnx
  File "/usr/local/lib/python3.6/dist-packages/onnx/__init__.py", line 8, in <module>
    from onnx.external_data_helper import load_external_data_for_model, write_external_data_tensors
  File "/usr/local/lib/python3.6/dist-packages/onnx/external_data_helper.py", line 10, in <module>
    from .onnx_pb import TensorProto, ModelProto
  File "/usr/local/lib/python3.6/dist-packages/onnx/onnx_pb.py", line 8, in <module>
    from .onnx_pb2 import *  # noqa
  File "/usr/local/lib/python3.6/dist-packages/onnx/onnx_pb2.py", line 7, in <module>
    from google.protobuf.internal import enum_type_wrapper
ModuleNotFoundError: No module named 'google.protobuf'

System: JetPack-4.4, Jetson Nano
I have installed protobuf-3.8.0" using the install_protobuf-3.8.0.sh script (with no errors)

Please help
Best Regards
David

**Comment by DavidDreven** [comment]
Solved by removingfile "__init__.py" in the "google" directory: /usr/local/lib/python3.6/dist-packages/protobuf-3.8.0-py3.6-linux-aarch64.egg/google.
