### ISSUE TITLE
yolo_to_onnx.py error 

### ISSUE THREAD

**Issue by noobgrow** [jkjung-avt/tensorrt_demos#285]
sir:
    when I try the  command :"python3 yolo_to_onnx.py -m yolov3-spp-416", error occurs as follows:
nvidia@nvidia-desktop:~/agx_yolo/tensorrt_demos/yolo$ python3 yolo_to_onnx.py -m yolov3-spp-416
Parsing DarkNet cfg file...
Building ONNX graph...
Traceback (most recent call last):
  File "yolo_to_onnx.py", line 955, in <module>
    main()
  File "yolo_to_onnx.py", line 938, in main
    verbose=True)
  File "yolo_to_onnx.py", line 458, in build_onnx_graph
    params)
  File "yolo_to_onnx.py", line 289, in load_upsample_scales
    name, TensorProto.FLOAT, shape, data)
  File "/usr/local/lib/python3.6/dist-packages/onnx/helper.py", line 173, in make_tensor
    getattr(tensor, field).extend(vals)
TypeError: 1.0 has type numpy.float32, but expected one of: int, long, float

Cound you help me? Thanks a lot!!

**Comment by jkjung-avt** [comment]
https://github.com/jkjung-avt/tensorrt_demos/issues/164
