### ISSUE TITLE
Converting ssd_mobilenet_v2_mnasfpn to TensorRT

### ISSUE THREAD

**Issue by codethief** [jkjung-avt/tensorrt_demos#333]
Hi JK,

First of all, thank you so much for all the work you've been putting into making TensorRT accessible for people like me! I honestly do not know what I would do without your reference code. :)

Here goes my question: Have you had any luck converting ssd_mobilenet_v2_mnasfpn to TensorRT? (I am aware MnasFPN was optimized rather for CPUs than for GPUs but in my application I was seeing much better accuracy than with ssd_mobilenet_v2. Plus, I also need to run my network on a CPU sometimes.)

Anyway, I extended your `build_engine.py` file to attempt the conversion but it didn't work. Judging from the [logs](https://github.com/jkjung-avt/tensorrt_demos/files/5851942/tensorrt_mnasfpn_test.txt), it's the `MultiscaleGridAnchorGenerator` that's causing the trouble and I've searched the entire internet for any pointers on how to solve this – to no avail. Do you happen to have an idea on how I could proceed here?

Thanks so much for your time!

--

For future reference, here's my code:

```python
'ssd_mobilenet_v2_mnasfpn_custom': {
    'input_pb':   os.path.abspath(os.path.join(
                      DIR_NAME, 'ssd_mobilenet_v2_mnasfpn_custom.pb')),
    'tmp_uff':    os.path.abspath(os.path.join(
                      DIR_NAME, 'ssd_mobilenet_v2_mnasfpn_custom.uff')),
    'output_bin': os.path.abspath(os.path.join(
                      DIR_NAME, 'TRT_ssd_mobilenet_v2_custom.bin')),

    # Different shape than all other networks, so I created an input_dims 
    # parameter for each model
    'input_dims': (3, 320, 320), 

    # Again different than for all other models, so I moved it to a parameter, too. 
    # I obtained it using an adapted version of 
    # https://stackoverflow.com/questions/51742805/ssd-anchors-in-tensorflow-detection-api
    'feature_map_shapes': [40, 20, 10, 5],  

    'num_classes': 3,  # 2 classes + background class
    'min_size': 0.2,
    'max_size': 0.95,
    'input_order': [1, 0, 2],  # order of loc_data, conf_data, priorbox_data
},
```

**Comment by jkjung-avt** [comment]
> [TensorRT] ERROR: UffParser: Validator error: MultiscaleGridAnchorGenerator/GridAnchorGenerator_3/Meshgrid_2/ExpandedShape_1/ones: Unsupported operation _Fill

TensorFlow Object Detection API code base is constantly evolving.  Based on this error, I'd think the "MultiscaleGridAnchorGenerator" in the "ssd_mobilenet_v2_mnasfpn" has changed quite a bit from older versions of the API.

By the way, the "MultiscaleGridAnchorGenerator" is used to be called "MultipleGridAnchorGenerator" in the older version of TensorFlow Object Detection API.  Refer to this line of source code:

https://github.com/jkjung-avt/tensorrt_demos/blob/451208d77af78d66f0fcbd70802b8bea1701eb5e/ssd/build_engine.py#L227

**Comment by codethief** [comment]
Hi JK, thanks so much for your quick response! 

Are you sure MultiscaleGridAnchorGenerator and MultipleGridAnchorGenerator are referring to the same entity? As far as I can see, the TensorFlow Object Detection repository still contains both,

https://github.com/tensorflow/models/blob/master/research/object_detection/anchor_generators/multiscale_grid_anchor_generator.py
https://github.com/tensorflow/models/blob/master/research/object_detection/anchor_generators/multiple_grid_anchor_generator.py

and they look quite different. Or is it that MultiscaleGridAnchorGenerator evolved out of MultipleGridAnchorGenerator and the latter is only being kept in the Object Detection repo for legacy/compatibility purposes?

In any case, I'll try to adapt `build_engine.py` as you suggested and will get back to you as soon as possible!

Again, thank you so much!

**Comment by jkjung-avt** [comment]
> Or is it that MultiscaleGridAnchorGenerator evolved out of MultipleGridAnchorGenerator and the latter is only being kept in the Object Detection repo for legacy/compatibility purposes?

I think this is likely the case.

**Comment by codethief** [comment]
The naive adaptation of `build_engine.py` didn't do the trick, unfortunately:

```
$ python3 build_engine.py ssd_mobilenet_v2_mnasfpn_custom
2021-01-24 17:28:44.711358: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.2
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
NOTE: UFF has been tested with TensorFlow 1.15.0.
WARNING: The version of TensorFlow installed on this system is not guaranteed to work with UFF.
UFF Version 0.6.9
=== Automatically deduced input nodes ===
[name: "Input"
op: "Placeholder"
attr {
  key: "dtype"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "shape"
  value {
    shape {
      dim {
        size: 1
      }
      dim {
        size: 3
      }
      dim {
        size: 320
      }
      dim {
        size: 320
      }
    }
  }
}
]
=========================================

Using output node NMS
Converting to UFF graph
Warning: No conversion function registered for layer: NMS_TRT yet.
Converting NMS as custom op: NMS_TRT
WARNING:tensorflow:From /usr/lib/python3.6/dist-packages/uff/converters/tensorflow/converter.py:226: The name tf.AttrValue is deprecated. Please use tf.compat.v1.AttrValue instead.

Warning: No conversion function registered for layer: FlattenConcat_TRT yet.
Converting concat_box_conf as custom op: FlattenConcat_TRT
Warning: No conversion function registered for layer: FlattenConcat_TRT yet.
Converting concat_box_loc as custom op: FlattenConcat_TRT
Warning: No conversion function registered for layer: GridAnchor_TRT yet.
Converting MultiscaleGridAnchorGenerator as custom op: GridAnchor_TRT
DEBUG [/usr/lib/python3.6/dist-packages/uff/converters/tensorflow/converter.py:143] Marking ['NMS'] as outputs
No. nodes: 1185
UFF Output written to /home/user/tensorrt_demos/ssd/ssd_mobilenet_v2_mnasfpn_custom.uff
UFF Text Output written to /home/user/tensorrt_demos/ssd/ssd_mobilenet_v2_mnasfpn_custom.pbtxt
#assertiongridAnchorPlugin.cpp,445
Aborted (core dumped)
```

I should mention that the script was hanging at `#assertiongridAnchorPlugin.cpp,445` for a couple minutes. Do you happen to know how I could debug this and find out where exactly things went wrong? Where does the core get dumped?

For definiteness, below is my modified `build_engine.py`. As discussed, I mapped `MultiscaleGridAnchorGenerator` to the `GridAnchor_TRT` op, similarly to `MultipleGridAnchorGenerator`:

```python

"""build_engine.py

This script converts a SSD model (pb) to UFF and subsequently builds
the TensorRT engine.

Input : ssd_mobilenet_v[1|2]_[coco|egohands].pb
Output: TRT_ssd_mobilenet_v[1|2]_[coco|egohands].bin
"""


import os
import ctypes
import argparse

import numpy as np
import uff
import tensorrt as trt
import graphsurgeon as gs


DIR_NAME = os.path.dirname(__file__)
LIB_FILE = os.path.abspath(os.path.join(DIR_NAME, 'libflattenconcat.so'))
MODEL_SPECS = {
    'ssd_mobilenet_v1_coco': {
        'input_pb':   os.path.abspath(os.path.join(
                          DIR_NAME, 'ssd_mobilenet_v1_coco.pb')),
        'tmp_uff':    os.path.abspath(os.path.join(
                          DIR_NAME, 'ssd_mobilenet_v1_coco.uff')),
        'output_bin': os.path.abspath(os.path.join(
                          DIR_NAME, 'TRT_ssd_mobilenet_v1_coco.bin')),
        'input_dims': (3, 300, 300),
        'feature_map_shapes': [19, 10, 5, 3, 2, 1],
        'num_classes': 91,
        'min_size': 0.2,
        'max_size': 0.95,
        'input_order': [0, 2, 1],  # order of loc_data, conf_data, priorbox_data
    },
    'ssd_mobilenet_v1_egohands': {
        'input_pb':   os.path.abspath(os.path.join(
                          DIR_NAME, 'ssd_mobilenet_v1_egohands.pb')),
        'tmp_uff':    os.path.abspath(os.path.join(
                          DIR_NAME, 'ssd_mobilenet_v1_egohands.uff')),
        'output_bin': os.path.abspath(os.path.join(
                          DIR_NAME, 'TRT_ssd_mobilenet_v1_egohands.bin')),
        'input_dims': (3, 300, 300),
        'feature_map_shapes': [19, 10, 5, 3, 2, 1],
        'num_classes': 2,
        'min_size': 0.05,
        'max_size': 0.95,
        'input_order': [0, 2, 1],  # order of loc_data, conf_data, priorbox_data
    },
    'ssd_mobilenet_v2_coco': {
        'input_pb':   os.path.abspath(os.path.join(
                          DIR_NAME, 'ssd_mobilenet_v2_coco.pb')),
        'tmp_uff':    os.path.abspath(os.path.join(
                          DIR_NAME, 'ssd_mobilenet_v2_coco.uff')),
        'output_bin': os.path.abspath(os.path.join(
                          DIR_NAME, 'TRT_ssd_mobilenet_v2_coco.bin')),
        'input_dims': (3, 300, 300),
        'feature_map_shapes': [19, 10, 5, 3, 2, 1],
        'num_classes': 91,
        'min_size': 0.2,
        'max_size': 0.95,
        'input_order': [1, 0, 2],  # order of loc_data, conf_data, priorbox_data
    },
    'ssd_mobilenet_v2_egohands': {
        'input_pb':   os.path.abspath(os.path.join(
                          DIR_NAME, 'ssd_mobilenet_v2_egohands.pb')),
        'tmp_uff':    os.path.abspath(os.path.join(
                          DIR_NAME, 'ssd_mobilenet_v2_egohands.uff')),
        'output_bin': os.path.abspath(os.path.join(
                          DIR_NAME, 'TRT_ssd_mobilenet_v2_egohands.bin')),
        'input_dims': (3, 300, 300),
        'feature_map_shapes': [19, 10, 5, 3, 2, 1],
        'num_classes': 2,
        'min_size': 0.05,
        'max_size': 0.95,
        'input_order': [0, 2, 1],  # order of loc_data, conf_data, priorbox_data
    },
    'ssd_mobilenet_v2_mnasfpn_custom': {
        'input_pb':   os.path.abspath(os.path.join(
                          DIR_NAME, 'ssd_mobilenet_v2_mnasfpn_custom.pb')),
        'tmp_uff':    os.path.abspath(os.path.join(
                          DIR_NAME, 'ssd_mobilenet_v2_mnasfpn_custom.uff')),
        'output_bin': os.path.abspath(os.path.join(
                          DIR_NAME, 'TRT_ssd_mobilenet_v2_custom.bin')),
        'input_dims': (3, 320, 320),
        'feature_map_shapes': [40, 20, 10, 5],
        'num_classes': 3, # = 2+1
        'min_size': 0.2,
        'max_size': 0.95,
        'input_order': [1, 0, 2],  # order of loc_data, conf_data, priorbox_data
    },
    'ssd_inception_v2_coco': {
        'input_pb':   os.path.abspath(os.path.join(
                          DIR_NAME, 'ssd_inception_v2_coco.pb')),
        'tmp_uff':    os.path.abspath(os.path.join(
                          DIR_NAME, 'ssd_inception_v2_coco.uff')),
        'output_bin': os.path.abspath(os.path.join(
                          DIR_NAME, 'TRT_ssd_inception_v2_coco.bin')),
        'input_dims': (3, 300, 300),
        'feature_map_shapes': [19, 10, 5, 3, 2, 1],
        'num_classes': 91,
        'min_size': 0.2,
        'max_size': 0.95,
        'input_order': [0, 2, 1],  # order of loc_data, conf_data, priorbox_data
    },
    'ssdlite_mobilenet_v2_coco': {
        'input_pb':   os.path.abspath(os.path.join(
                          DIR_NAME, 'ssdlite_mobilenet_v2_coco.pb')),
        'tmp_uff':    os.path.abspath(os.path.join(
                          DIR_NAME, 'ssdlite_mobilenet_v2_coco.uff')),
        'output_bin': os.path.abspath(os.path.join(
                          DIR_NAME, 'TRT_ssdlite_mobilenet_v2_coco.bin')),
        'input_dims': (3, 300, 300),
        'feature_map_shapes': [19, 10, 5, 3, 2, 1],
        'num_classes': 91,
        'min_size': 0.2,
        'max_size': 0.95,
        'input_order': [0, 2, 1],  # order of loc_data, conf_data, priorbox_data
    },
}
DEBUG_UFF = False


def replace_addv2(graph):
    """Replace all 'AddV2' in the graph with 'Add'.

    'AddV2' is not supported by UFF parser.

    Reference:
    1. https://github.com/jkjung-avt/tensorrt_demos/issues/113#issuecomment-629900809
    """
    for node in graph.find_nodes_by_op('AddV2'):
        gs.update_node(node, op='Add')
    return graph


def replace_fusedbnv3(graph):
    """Replace all 'FusedBatchNormV3' in the graph with 'FusedBatchNorm'.

    'FusedBatchNormV3' is not supported by UFF parser.

    Reference:
    1. https://devtalk.nvidia.com/default/topic/1066445/tensorrt/tensorrt-6-0-1-tensorflow-1-14-no-conversion-function-registered-for-layer-fusedbatchnormv3-yet/post/5403567/#5403567
    2. https://github.com/jkjung-avt/tensorrt_demos/issues/76#issuecomment-607879831
    """
    for node in graph.find_nodes_by_op('FusedBatchNormV3'):
        gs.update_node(node, op='FusedBatchNorm')
    return graph


def add_anchor_input(graph):
    """Add the missing const input for the GridAnchor node.

    Reference:
    1. https://www.minds.ai/post/deploying-ssd-mobilenet-v2-on-the-nvidia-jetson-and-nano-platforms
    """
    data = np.array([1, 1], dtype=np.float32)
    anchor_input = gs.create_node('AnchorInput', 'Const', value=data)
    graph.append(anchor_input)
    graph.find_nodes_by_op('GridAnchor_TRT')[0].input.insert(0, 'AnchorInput')
    return graph

def add_plugin(graph, model, spec):
    """add_plugin

    Reference:
    1. https://github.com/AastaNV/TRT_object_detection/blob/master/config/model_ssd_mobilenet_v1_coco_2018_01_28.py
    2. https://github.com/AastaNV/TRT_object_detection/blob/master/config/model_ssd_mobilenet_v2_coco_2018_03_29.py
    3. https://devtalk.nvidia.com/default/topic/1050465/jetson-nano/how-to-write-config-py-for-converting-ssd-mobilenetv2-to-uff-format/post/5333033/#5333033
    """
    numClasses = spec['num_classes']
    minSize = spec['min_size']
    maxSize = spec['max_size']
    inputOrder = spec['input_order']

    all_assert_nodes = graph.find_nodes_by_op('Assert')
    graph.remove(all_assert_nodes, remove_exclusive_dependencies=True)

    all_identity_nodes = graph.find_nodes_by_op('Identity')
    graph.forward_inputs(all_identity_nodes)

    Input = gs.create_plugin_node(
        name='Input',
        op='Placeholder',
        shape=(1,) + spec['input_dims']
    )

    PriorBox_MultipleGridAnchorGenerator = gs.create_plugin_node(
        name='MultipleGridAnchorGenerator',
        op='GridAnchor_TRT',
        minSize=minSize,  # was 0.2
        maxSize=maxSize,  # was 0.95
        aspectRatios=[1.0, 2.0, 0.5, 3.0, 0.33],
        variance=[0.1, 0.1, 0.2, 0.2],
        featureMapShapes=spec['feature_map_shapes'],
        numLayers=6
    )
    PriorBox_MultiscaleGridAnchorGenerator = gs.create_plugin_node(
        name='MultiscaleGridAnchorGenerator',
        op='GridAnchor_TRT',
        minSize=minSize,  # was 0.2
        maxSize=maxSize,  # was 0.95
        aspectRatios=[1.0, 2.0, 0.5, 3.0, 0.33],
        variance=[0.1, 0.1, 0.2, 0.2],
        featureMapShapes=spec['feature_map_shapes'],
        numLayers=6
    )

    NMS = gs.create_plugin_node(
        name='NMS',
        op='NMS_TRT',
        shareLocation=1,
        varianceEncodedInTarget=0,
        backgroundLabelId=0,
        confidenceThreshold=0.3,  # was 1e-8
        nmsThreshold=0.6,
        topK=100,
        keepTopK=100,
        numClasses=numClasses,  # was 91
        inputOrder=inputOrder,
        confSigmoid=1,
        isNormalized=1
    )

    concat_priorbox = gs.create_node(
        'concat_priorbox',
        op='ConcatV2',
        axis=2
    )

    if trt.__version__[0] >= '7':
        concat_box_loc = gs.create_plugin_node(
            'concat_box_loc',
            op='FlattenConcat_TRT',
            axis=1,
            ignoreBatch=0
        )
        concat_box_conf = gs.create_plugin_node(
            'concat_box_conf',
            op='FlattenConcat_TRT',
            axis=1,
            ignoreBatch=0
        )
    else:
        concat_box_loc = gs.create_plugin_node(
            'concat_box_loc',
            op='FlattenConcat_TRT'
        )
        concat_box_conf = gs.create_plugin_node(
            'concat_box_conf',
            op='FlattenConcat_TRT'
        )

    namespace_for_removal = [
        'ToFloat',
        'image_tensor',
        'Preprocessor/map/TensorArrayStack_1/TensorArrayGatherV3',
    ]
    namespace_plugin_map = {
        'MultipleGridAnchorGenerator': PriorBox_MultipleGridAnchorGenerator,
        'MultiscaleGridAnchorGenerator': PriorBox_MultiscaleGridAnchorGenerator,
        'Postprocessor': NMS,
        'Preprocessor': Input,
        'ToFloat': Input,
        'Cast': Input,  # added for models trained with tf 1.15+
        'image_tensor': Input,
        'MultipleGridAnchorGenerator/Concatenate': concat_priorbox,  # for 'ssd_mobilenet_v1_coco'
        'Concatenate': concat_priorbox,  # for other models
        'concat': concat_box_loc,
        'concat_1': concat_box_conf
    }

    graph.remove(graph.find_nodes_by_path(['Preprocessor/map/TensorArrayStack_1/TensorArrayGatherV3']), remove_exclusive_dependencies=False)  # for 'ssd_inception_v2_coco'

    graph.collapse_namespaces(namespace_plugin_map)
    graph = replace_addv2(graph)
    graph = replace_fusedbnv3(graph)

    if 'image_tensor:0' in graph.find_nodes_by_name('Input')[0].input:
        graph.find_nodes_by_name('Input')[0].input.remove('image_tensor:0')
    if 'Input' in graph.find_nodes_by_name('NMS')[0].input:
        graph.find_nodes_by_name('NMS')[0].input.remove('Input')
    # Remove the Squeeze to avoid "Assertion 'isPlugin(layerName)' failed"
    graph.forward_inputs(graph.find_node_inputs_by_name(graph.graph_outputs[0], 'Squeeze'))
    if 'anchors' in [node.name for node in graph.graph_outputs]:
        graph.remove('anchors', remove_exclusive_dependencies=False)
    if len(graph.find_nodes_by_op('GridAnchor_TRT')[0].input) < 1:
        graph = add_anchor_input(graph)
    if 'NMS' not in [node.name for node in graph.graph_outputs]:
        graph.remove(graph.graph_outputs, remove_exclusive_dependencies=False)
        if 'NMS' not in [node.name for node in graph.graph_outputs]:
            # We expect 'NMS' to be one of the outputs
            raise RuntimeError('bad graph_outputs')

    return graph


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('model', type=str, choices=list(MODEL_SPECS.keys()))
    args = parser.parse_args()

    # initialize
    if trt.__version__[0] < '7':
        ctypes.CDLL(LIB_FILE)
    TRT_LOGGER = trt.Logger(trt.Logger.INFO)
    trt.init_libnvinfer_plugins(TRT_LOGGER, '')

    # compile the model into TensorRT engine
    model = args.model
    spec = MODEL_SPECS[model]
    dynamic_graph = add_plugin(
        gs.DynamicGraph(spec['input_pb']),
        model,
        spec)
    _ = uff.from_tensorflow(
        dynamic_graph.as_graph_def(),
        output_nodes=['NMS'],
        output_filename=spec['tmp_uff'],
        text=True,
        debug_mode=DEBUG_UFF)
    with trt.Builder(TRT_LOGGER) as builder, builder.create_network() as network, trt.UffParser() as parser:
        builder.max_workspace_size = 1 << 28
        builder.max_batch_size = 1
        builder.fp16_mode = True

        parser.register_input('Input', spec['input_dims'])
        parser.register_output('MarkOutput_0')
        parser.parse(spec['tmp_uff'], network)
        engine = builder.build_cuda_engine(network)

        buf = engine.serialize()
        with open(spec['output_bin'], 'wb') as f:
            f.write(buf)


if __name__ == '__main__':
    main()
```

**Comment by codethief** [comment]
Never mind my previous comment, I had made a mistake and it does seem to work to some degree – I'm now getting a much "nicer" error (see below).

My mistake was that, if I understand the [grid anchor plugin's README](https://github.com/NVIDIA/TensorRT/blob/master/plugin/gridAnchorPlugin/README.md) correctly, the `numLayers` parameter must be the length of the given `featureMapShapes` list. I've adjusted my code accordingly:

```python
    PriorBox_MultiscaleGridAnchorGenerator = gs.create_plugin_node(
        name='MultiscaleGridAnchorGenerator',
        op='GridAnchor_TRT',
        minSize=minSize,  # was 0.2
        maxSize=maxSize,  # was 0.95
        aspectRatios=[1.0, 2.0, 0.5, 3.0, 0.33],
        variance=[0.1, 0.1, 0.2, 0.2],
        featureMapShapes=spec['feature_map_shapes'],
        numLayers=len(spec['feature_map_shapes']),
    )
```

(Once again, I'm attaching [the full code](https://github.com/jkjung-avt/tensorrt_demos/files/5862834/build_engine.py.txt) for definiteness.)

The script now fails at the following step:

```
[TensorRT] VERBOSE: UFFParser: Parsing FeatureExtractor/MnasFPN/cell_0/block_0/input_1/Conv1x1/weights[Op: Const].
[TensorRT] VERBOSE: UFFParser: FeatureExtractor/MnasFPN/cell_0/block_0/input_1/Conv1x1/weights -> [1,1,256,208]
[TensorRT] VERBOSE: UFFParser: Applying order forwarding to: FeatureExtractor/MnasFPN/cell_0/block_0/input_1/Conv1x1/weights
[TensorRT] VERBOSE: UFFParser: Parsing FeatureExtractor/MnasFPN/cell_0/block_0/input_1/Conv1x1/Conv2D[Op: Conv]. Inputs: FeatureExtractor/MobilenetV2/expanded_conv_16/project/BatchNorm/FusedBatchNormV3, FeatureExtractor/MnasFPN/cell_0/block_0/input_1/Conv1x1/weights
[TensorRT] VERBOSE: UFFParser: FeatureExtractor/MnasFPN/cell_0/block_0/input_1/Conv1x1/Conv2D -> [208,10,10]
[TensorRT] VERBOSE: UFFParser: Applying order forwarding to: FeatureExtractor/MnasFPN/cell_0/block_0/input_1/Conv1x1/Conv2D
[TensorRT] VERBOSE: UFFParser: Parsing FeatureExtractor/MnasFPN/cell_0/block_0/input_1/Conv1x1/BatchNorm/gamma[Op: Const].
[TensorRT] VERBOSE: UFFParser: FeatureExtractor/MnasFPN/cell_0/block_0/input_1/Conv1x1/BatchNorm/gamma -> [208]
[TensorRT] VERBOSE: UFFParser: Applying order forwarding to: FeatureExtractor/MnasFPN/cell_0/block_0/input_1/Conv1x1/BatchNorm/gamma
[TensorRT] VERBOSE: UFFParser: Parsing FeatureExtractor/MnasFPN/cell_0/block_0/input_1/Conv1x1/BatchNorm/beta[Op: Const].
[TensorRT] VERBOSE: UFFParser: FeatureExtractor/MnasFPN/cell_0/block_0/input_1/Conv1x1/BatchNorm/beta -> [208]
[TensorRT] VERBOSE: UFFParser: Applying order forwarding to: FeatureExtractor/MnasFPN/cell_0/block_0/input_1/Conv1x1/BatchNorm/beta
[TensorRT] VERBOSE: UFFParser: Parsing FeatureExtractor/MnasFPN/cell_0/block_0/input_1/Conv1x1/BatchNorm/moving_mean[Op: Const].
[TensorRT] VERBOSE: UFFParser: FeatureExtractor/MnasFPN/cell_0/block_0/input_1/Conv1x1/BatchNorm/moving_mean -> [208]
[TensorRT] VERBOSE: UFFParser: Applying order forwarding to: FeatureExtractor/MnasFPN/cell_0/block_0/input_1/Conv1x1/BatchNorm/moving_mean
[TensorRT] VERBOSE: UFFParser: Parsing FeatureExtractor/MnasFPN/cell_0/block_0/input_1/Conv1x1/BatchNorm/moving_variance[Op: Const].
[TensorRT] VERBOSE: UFFParser: FeatureExtractor/MnasFPN/cell_0/block_0/input_1/Conv1x1/BatchNorm/moving_variance -> [208]
[TensorRT] VERBOSE: UFFParser: Applying order forwarding to: FeatureExtractor/MnasFPN/cell_0/block_0/input_1/Conv1x1/BatchNorm/moving_variance
[TensorRT] VERBOSE: UFFParser: Parsing FeatureExtractor/MnasFPN/cell_0/block_0/input_1/Conv1x1/BatchNorm/FusedBatchNormV3[Op: BatchNorm]. Inputs: FeatureExtractor/MnasFPN/cell_0/block_0/input_1/Conv1x1/Conv2D, FeatureExtractor/MnasFPN/cell_0/block_0/input_1/Conv1x1/BatchNorm/gamma, FeatureExtractor/MnasFPN/cell_0/block_0/input_1/Conv1x1/BatchNorm/beta, FeatureExtractor/MnasFPN/cell_0/block_0/input_1/Conv1x1/BatchNorm/moving_mean, FeatureExtractor/MnasFPN/cell_0/block_0/input_1/Conv1x1/BatchNorm/moving_variance
[TensorRT] VERBOSE: UFFParser: FeatureExtractor/MnasFPN/cell_0/block_0/input_1/Conv1x1/BatchNorm/FusedBatchNormV3 -> [208,10,10]
[TensorRT] VERBOSE: UFFParser: Applying order forwarding to: FeatureExtractor/MnasFPN/cell_0/block_0/input_1/Conv1x1/BatchNorm/FusedBatchNormV3
[TensorRT] VERBOSE: UFFParser: Parsing FeatureExtractor/MnasFPN/cell_0/block_0/input_1/nearest_neighbor_upsampling/stack[Op: Stack]. Inputs: FeatureExtractor/MnasFPN/cell_0/block_0/input_1/Conv1x1/BatchNorm/FusedBatchNormV3, FeatureExtractor/MnasFPN/cell_0/block_0/input_1/Conv1x1/BatchNorm/FusedBatchNormV3
[TensorRT] ERROR: UffParser: Parser error: FeatureExtractor/MnasFPN/cell_0/block_0/input_1/nearest_neighbor_upsampling/stack: stack only support for Constants nodes as input for now
[TensorRT] ERROR: Network must have at least one output
[TensorRT] ERROR: Network validation failed.
Traceback (most recent call last):
  File "build_engine.py", line 344, in <module>
    main()
  File "build_engine.py", line 338, in main
    buf = engine.serialize()
AttributeError: 'NoneType' object has no attribute 'serialize'
```

([Full logs](https://github.com/jkjung-avt/tensorrt_demos/files/5862839/logs.txt))

Unfortunately, I seem to have reached a dead end if interpret [this answer on the Nvidia forums](https://forums.developer.nvidia.com/t/tensorrt-stack-stack-only-support-for-constants-nodes-as-input-for-now/109172/2) correctly. :(

**Comment by jkjung-avt** [comment]
> [TensorRT] ERROR: UffParser: Parser error: FeatureExtractor/MnasFPN/cell_0/block_0/input_1/nearest_neighbor_upsampling/stack: stack only support for Constants nodes as input for now

The "Stack" op could probably be replaced by a couple of "Reshape"s and a "Concat".  If you are able to use graphsurgeon to modify the graph, it might be worth a try.

Reference: https://stackoverflow.com/questions/41534593/why-would-i-ever-use-tf-concat-instead-of-tf-stack

**Comment by codethief** [comment]
Oops, forgot to answer. I'll be giving ONNX a shot in the coming days. If that fails, I'll try to replace the Stack op. Thanks so much for your help so far! I'll report back!
