### ISSUE TITLE
unable to convert custom yolov4x-mish  model into onnx -buffer is too small for requested array 

### ISSUE THREAD

**Issue by akashAD98** [jkjung-avt/tensorrt_demos#470]
I have checked all previous issues, my cfg & weight file has the same name   & it's working fine with darknet api.
Even i was able to convert another custom mish models ,but I'm getting issues  with this model . can you please help me where is the problem? Thanks 
I have attached cfg here :
[yolov4-mish_25_weapons_DA_BG_Extra.cfg.txt](https://github.com/jkjung-avt/tensorrt_demos/files/7031281/yolov4-mish_25_weapons_DA_BG_Extra.cfg.txt)

here is error im getting:

Traceback (most recent call last):
  File "yolo_to_onnx.py", line 1014, in <module>
    main()
  File "yolo_to_onnx.py", line 999, in main
    yolo_model_def = builder.build_onnx_graph(
  File "yolo_to_onnx.py", line 537, in build_onnx_graph
    initializer_layer, inputs_layer = weight_loader.load_conv_weights(
  File "yolo_to_onnx.py", line 411, in load_conv_weights
    conv_init, conv_input = self._create_param_tensors(
  File "yolo_to_onnx.py", line 439, in _create_param_tensors
    param_name, param_data, param_data_shape = self._load_one_param_type(
  File "yolo_to_onnx.py", line 467, in _load_one_param_type
    param_data = np.ndarray(
TypeError: buffer is too small for requested array

**Comment by akashAD98** [comment]
opps my weight file was corrupted at the time of uploading weight.. its solved my issue by again uploading new weight
