### ISSUE TITLE
AssertionError question

### ISSUE THREAD

**Issue by hotudon** [jkjung-avt/tensorrt_demos#569]
Hello,

I was able to run your demo fine before but now I am running into this issue with the val2017 data set listed in your demo.

Loading and preparing results...
Traceback (most recent call last):
  File "eval_ssd.py", line 109, in <module>
    main()
  File "eval_ssd.py", line 99, in main
    cocoDt = cocoGt.loadRes(results_file)
  File "/home/hotudon/.local/lib/python3.6/site-packages/pycocotools/coco.py", line 317, in loadRes
    'Results do not correspond to current coco set'
AssertionError: Results do not correspond to current coco set

any help is appreciated

**Comment by hotudon** [comment]
closing issue.   I was messing around with the code to see how I can use it for other data set.   It was a mismatch in how I call the data set vs what was in the annotation.
